# configuration for a clojure/deps.edn application
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.697
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Run tests
          command: clojure -M:test:runner
      - run:
          name: check coverage
          command: clojure -M:test:coverage
